### ISSUE TITLE
Fail to build on Qt 5.7.1 on linux arm

### ISSUE THREAD

**Issue by Fonger** [BrigJS/brig#15]
On raspberry pi 3

```
make: Entering directory '/home/pi/xxx/node_modules/brig/build'
  CXX(target) Release/obj.target/brig/build/src/moc_eventdispatcher.o
  CXX(target) Release/obj.target/brig/build/src/brig.o
In file include from ../src/brig.h:32:0,
                     from ../src/brig.cpp:2:
../src/DynamicQMetaObjectBuilder.h:6:43: fatal error: internal/qmetaobjectbuilder_p.h: No such file or directory
 #include <internal/qmetaobjectbuilder_p.h>

compilation terminalted.
```
